# infra/ansible/inventory/aws_ec2.yml
# Inventário dinâmico — descobre as EC2 pelo tag Project + Name
plugin: amazon.aws.aws_ec2

regions:
  - eu-central-1

filters:
  tag:Project: mini-ecommerce
  instance-state-name: running

keyed_groups:
  # Cria grupos pelo tag Name: api_gateway, catalog_service, etc.
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - ip-address   # usa IP público para as instâncias públicas (api-gateway)
  - private-ip-address

compose:
  #endereço que o Ansible vai usar para se ligar à máquina via SSH.
  ansible_host: public_ip_address | default(private_ip_address)
